---

- name: Create Settings Access Token
  include_tasks: access-token.yml

- name: Enable Application Security Settings
  include_tasks: application-security.yml

- name: Enable Log Storage Settings
  include_tasks: log-settings.yml

- name: Enable Business Events Settings
  include_tasks: business-events.yml

- name: Enable Kubernetes App and Cluster Monitoring
  include_tasks: kubernetes-monitoring.yml
