---

- name: Create Dynatrace Settings Token
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/apiTokens"
    method: POST
    status_code: [200, 201]
    body:
      name: "Dynatrace Settings Token"
      scopes:
        - settings.read
        - settings.write
        - securityProblems.write
    body_format: json
    headers:
      Authorization: "Api-Token {{ dynatrace_environment_access_token }}"
  register: dynatrace_settings_token_result


- name: Ensure runtime vulnerability detection settings are configured
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:appsec.runtime-vulnerability-detection"
        schemaVersion: "3.12.1"
        scope: "environment"
        value:
          enableRuntimeVulnerabilityDetection: true
          globalMonitoringModeTPV: "MONITORING_ON"
          technologies:
            enableDotNet: true
            enableDotNetRuntime: true
            enableGo: true
            enableJava: true
            enableJavaRuntime: true
            enableKubernetes: true
            enableNodeJs: true
            enableNodeJsRuntime: true
            enablePython: true
            enablePythonRuntime: true
            enablePhp: true
          enableCodeLevelVulnerabilityDetection: true
          globalMonitoringModeJava: "MONITORING_ON"
          globalMonitoringModeDotNet: "MONITORING_ON"
          globalMonitoringModeGo: "MONITORING_ON"
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_appsec_result
  failed_when: false

- name: Ensure log storage settings are configured
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:logmonitoring.log-storage-settings"
        schemaVersion: "1.0.18"
        scope: "environment"
        value:
          enabled: true
          config-item-title: "Custom: Ingest all logs"
          send-to-storage: true
          matchers: []
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_log_ingest
  failed_when: false

- name: Enable Kubernetes app & Smartscape settings
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:app-transition.kubernetes"
        schemaVersion: "1.0.3"
        scope: "environment"
        value:
          kubernetesAppOptions:
            enableKubernetesApp: true
            enableKubernetesSmartscape: true
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_kubernetes_app
  failed_when: false

- name: Enable OneAgent Feature - Node.js Business Events
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:oneagent.features"
        schemaVersion: "1.5.10"
        scope: "environment"
        value:
          enabled: true
          instrumentation: true
          key: "SENSOR_NODEJS_BIZEVENTS_HTTP_INCOMING"
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_oneagent_nodejs_bizevents
  failed_when: false

- name: Enable OneAgent Feature - Webserver Business Events
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:oneagent.features"
        schemaVersion: "1.5.10"
        scope: "environment"
        value:
          enabled: true
          instrumentation: true
          key: "SENSOR_WEBSERVER_BIZEVENTS_HTTP_INCOMING"
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_oneagent_webserver_bizevents
  failed_when: false

- name: Fetch Dynatrace Kubernetes cluster MEID from DynaKube status
  shell: >
    kubectl -n dynatrace get dynakube -o jsonpath='{.items[0].status.kubernetesClusterMEID}'
  register: dt_k8s_cluster_meid
  failed_when: false

- name: Set Dynatrace Kubernetes cluster scope fact
  set_fact:
    dynatrace_k8s_cluster_meid: "{{ dt_k8s_cluster_meid.stdout }}"

- name: Print Dynatrace Kubernetes cluster MEID
  ansible.builtin.debug:
    msg: "kubernetesClusterMEID: {{ dt_k8s_cluster_meid.stdout }}"

- name: Enable Kubernetes App Monitoring on Cluster
  uri:
    url: "{{ dynatrace_environment_url }}/api/v2/settings/objects"
    method: POST
    headers:
      Accept: "application/json; charset=utf-8"
      Content-Type: "application/json; charset=utf-8"
      Authorization: "Api-Token {{ dynatrace_settings_token_result.json.token }}"
    body:
      - schemaId: "builtin:app-transition.kubernetes"
        schemaVersion: "1.1"
        scope: "{{ dynatrace_k8s_cluster_meid }}"
        value:
          kubernetesAppOptions:
            enableKubernetesApp: true
    body_format: json
    return_content: true
    status_code: [200, 201, 409]
  register: dt_settings_enable_kubernetes_app_monitoring
  failed_when: false
