---
vscode_domain: "vscode.{{ ingress_domain }}"
vscode_namespace: "vscode"
vscode_password: "{{ instance_password }}"
private_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
local_ingress_port: 8080
vscode_version: "4.109.2" # https://github.com/coder/code-server
vscode_extensions:
  - "/mnt/volume/extensions/dynatrace.dynatrace-debugging-extension-2.3.0.vsix"