---
- name: Dynatrace University Sandbox - Core
  hosts: localhost
  connection: local
  vars_files: 
    - ./ansible_config_vars.yml
  tasks:
    - include_role:
        name: kubernetes
    - include_role:
        name: dynatrace-operator
    - include_role:
        name: dynatrace-settings
    - include_role:
        name: vscode