---
- name: Dynatrace University Sandbox - Bare
  hosts: localhost
  connection: local
  vars:
    ansible_config_file_path: './aether_config_vars.yml'
  tasks:
    - name: Load aether config vars
      include_vars:
        file: "{{ ansible_config_file_path }}"

    - name: Initialize business event facts
      include_role:
        name: business-events
        tasks_from: bizevent-set-facts.yml

    - name: Send START business event
      include_role:
        name: business-events
        tasks_from: bizevent-send.yml
      vars:
        bizevent_type: "aether-instance-sandbox-start"
        bizevent_category: "INFO"

    - block:
        - name: Load sandbox config vars
          include_vars:
            file: ./ansible_config_vars.yml

        - name: Deploy Kubernetes base
          include_role:
            name: kubernetes

        - name: Deploy VS Code Server
          include_role:
            name: vscode

        - name: Display access links
          include_role:
            name: display-links
          vars:
            sandbox_scenario: "bare"

        - name: Send SUCCESS business event
          include_role:
            name: business-events
            tasks_from: bizevent-send.yml
          vars:
            bizevent_type: "aether-instance-sandbox-complete"
            bizevent_category: "INFO"

      rescue:
        - name: Send FAILURE business event
          include_role:
            name: business-events
            tasks_from: bizevent-send.yml
          vars:
            bizevent_type: "aether-instance-sandbox-failure"
            bizevent_category: "FAILURE"