---

- name: Set acceptable response codes
  set_fact:
    acceptable_response_codes: [200, 201, 202, 204, 301, 302, 304, 403, 401]

- name: Set Application URL
  set_fact:
    app_url: "{{ verify_url }}"

- name: Debug the application URL
  debug:
    msg: "Application URL to health check: {{ app_url }}"

- name: Check application availability with curl
  command: "curl -o /dev/null -s -w \"%{http_code}\" {{ app_url }}"
  register: curl_response
  until: curl_response.rc == 0 and (curl_response.stdout | int in acceptable_response_codes)
  retries: 15
  delay: 10
  failed_when: curl_response.rc != 0

- name: Check if application is accessible
  debug:
    msg: "Application with the URL {{ app_url }} is accessible. Response: {{ curl_response.stdout }}"
  when: curl_response.rc == 0 and (curl_response.stdout | int in acceptable_response_codes)

- name: Fail if application is not accessible
  fail:
    msg: "Application with the URL {{ app_url }} is not accessible. Response: {{ curl_response.stdout }}"
  when: curl_response.rc != 0 or (curl_response.stdout | int not in acceptable_response_codes)